# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpages', '0013_auto_20180413_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='modularpage',
            name='zen_nav',
            field=models.BooleanField(default=False, help_text='For secondary nav pages or minisites, turn this on to collapse the primary nav by deault and add a toggle hamburger.'),
        ),
        migrations.AddField(
            model_name='primarypage',
            name='zen_nav',
            field=models.BooleanField(default=False, help_text='For secondary nav pages or minisites, turn this on to collapse the primary nav by deault and add a toggle hamburger.'),
        ),
    ]
